### PR TITLE
Refactor compiler

### PR DESCRIPTION
**Pull request by exodrifter**
The Rumor compiler has been completely rewritten in order to support more robust expression string parsing.

### Added
* You can now add the enum argument `cant_skip` to the end of a pause statement
  to ignore advances until the pause ends
* You can now add the enum argument `no_wait` to the end of an add or say
  statement to auto advance the dialog
* Variable substitution with `{` and `}` in strings is now supported

### Changed
* The compiler no longer uses a tokenizer except when parsing expressions
* Compiler errors are more specific and descriptive
* The `Exodrifter.Rumor.Lang` namespace has been renamed to
  `Exodrifter.Rumor.Language`
* All unit tests and examples are wrapped in a `UNITY_EDITOR` ifdef to make
  it easier to use this repository as a submodule in non-unity project
* Bindings are no longer stored in `Rumor`; instead, it is now stored in
  `Bindings`
* `Rumor.Run` has been renamed to `Rumor.Start` in order to match the language
  used in C# `Thread.Start` and Unity's `StartCoroutine` method to improve
  consistency

### CODE REVIEW

**Comment by exodrifter** [comment]
@dhowe and @SenshiSentou, I would appreciate feedback from the both of you on this PR if you have time. The changes I've made should fix the problems or implements the features you have asked for.

**Comment by SenshiSentou** [comment]
Hey, congrats on and thanks for the rewrite! Much appreciated.

I did find a few bugs/ regressions unfortunately:

The following script:
    $me = "Hero" 
    say me "Boop boop, I'm me!"

throws the following error:
    UnknownCommandException: Found unknown command "$me" at line 1, column 5 (index 4)

At first I thought it might be related to #53, but it seems the culprit is simply that there isn't a space after the `$`. `$ me = "Hero"` works as expected. This goes for binding calls as well.

If this is expected/ desired behaviour that's fine, but then it's inconsistent with variable substitution, which does allow both `{var}` and `{ var }`.

---

Speaking of variable substitution, escaping the brackets produces a fun result. `\{var}` shows up in text as `\var}` rather than the expected literal `{var}`.

---

Lastly, `no_wait` works great, expect in this scenario it got confused:
    say me "..." no_wait

which throws:
    NullReferenceException: Left argument to dot operator is null
    Exodrifter.Rumor.Expressions.DotExpression.Evaluate (Exodrifter.Rumor.Engine.Scope scope, Exodrifter.Rumor.Engine.Bindings bindings) (at Assets/Plugins/Rumor/Expressions/DotExpression.cs:24)
    [....]

**Comment by exodrifter** [comment]
Thanks for taking a look and giving feedback!

I can see why you may want to not have a space after `$`, but the reason for that is because it's a command like `add`, which always have a space after them. I went ahead and make a fix that will allow you to not have a space after `$`, but you'll still need a space after all of the other commands.

I also added a fix for '"\{"` not escaping correctly and fixed the corresponding test; and the float parsing error you mentioned and added a new corresponding test `CompileExpressionFloat`.

Let me know if you have any other problems/suggestions.

**Comment by exodrifter** [comment]
Oh, as an aside, I also found a bug that prevents the compiler from working correctly with carriage returns. I've fixed that as well.

**Pull request merged**
